namespace NeptuneTeaAPI.Models;

/// <summary>
/// Represents a sinle menu item (drink) at Neptune Tea
/// This class maps to a database table and contains all the info for one drink.
/// </summary>
public class MenuItem
{
    /// <summary>
    /// Unique identifier for each menu item (auto-generated by database)
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Name of the drink (e.g, classic milk tea)
    /// </summary>
    public required string Name {get; set;} // required = safety net to avoids bugs and random null values.

    /// <summary>
    /// Short description of the drink (e.g., Traditional black tea with cream milk)
    /// </summary>
    public required string Description {get; set;} 

    /// <summary>
    /// Price in dollars ( e.g. $5.50)
    /// </summary>
    public decimal Price {get; set;}

    /// <summary>
    /// Category this drink belongs to (MilkTea, FruitTea, etc)
    /// </summary>
    public required Category Category {get; set;} // 1st category = enum type | 2nd category = property name
}

