namespace NeptuneTeaAPI.Models;

/// <summary>
/// Represents a customer order for a drink.
/// Stores what was ordered and when.
/// </summary>
public class Order
{
    /// <summary>
    /// Unique identifier for each order (auto-generated by database)
    /// </summary>
    public int Id {get; set;}

    /// <summary>
    /// Name of the item that was ordered (e.g., Coconut Milk Tea")
    /// </summary>
    public required string ItemName {get; set;}

    /// <summary>
    /// How many of this item were ordered (default is 1)
    /// </summary>
    public int Quantity {get; set;} = 1;

    /// <summary>
    /// When this order was placed (automatically set to current time)
    /// </summary>
    public DateTime OrderdAt {get; set;}
}


